In [1]:
import pandas as pd 
import numpy as np

In [2]:
caract_df = pd.read_csv("Dataset - Sécurité Routière.xlsx - caract 2024.csv")
caract_df.head()

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long
0,202400000001,25,3,2024,7:40,2,70,70285,1,1,5,1,D438,47.562770,6.758320
1,202400000002,20,3,2024,15:05,1,21,21054,2,3,7,6,HOTEL DIEU (RUE DE L'),47.021090,4.837550
2,202400000003,22,3,2024,19:30,2,15,15012,1,1,1,6,Allée des Tilleuls,44.902384,2.496418
3,202400000004,24,3,2024,17:50,1,14,14118,2,3,7,3,128 Rue d'Authie,49.191660,-0.398510
4,202400000005,25,3,2024,19:35,5,13,13106,1,3,2,5,BEDOULE (CHEMIN DE LA),43.390000,5.350000

In [3]:
caract_df.isnull().sum()

Num_Acc       0
jour          0
mois          0
an            0
hrmn          0
lum           0
dep           0
com           0
agg           0
int           0
atm           0
col           0
adr        2310
lat           0
long          0
dtype: int64

In [4]:
vehi_df = pd.read_csv("Dataset - Sécurité Routière.xlsx - véhi imma 2024.csv")

In [5]:
vehi_df.head()

,Id_accident,Lettre Conventionnelle Véhicule,Année,Lieu Admin Actuel - Territoire Nom,CNIT,Catégorie véhicule,Age véhicule
0,67 230 442,A,2024,Métropole,N10MCWCTMU3L706,VU,3.0
1,67 230 442,B,2024,Métropole,MRE3306AW885,VT,22.0
2,67 230 442,C,2024,Métropole,N10VWGCTN23U973,VT,7.0
3,67 230 443,A,2024,Métropole,LYM94J30J537,Moto lourde,14.0
4,67 230 444,A,2024,Métropole,WDF639603135376,VU,15.0

In [6]:
vehi_df.isnull().sum()

Id_accident                               0
Lettre Conventionnelle Véhicule           1
Année                                     0
Lieu Admin Actuel - Territoire Nom        0
CNIT                                  20028
Catégorie véhicule                        0
Age véhicule                           5395
dtype: int64