In [41]:
import pandas as pd

In [42]:
# On passe en latin1 pour gérer les accents français (é, à, è...)
radar_df = pd.read_csv(
    "jeu-de-donnees-liste-des-radars-fixes-en-france-12-2025.csv", 
    encoding="latin1", 
    sep=";"
)

# On vérifie si les troupes sont en place
radar_df

,Numéro de radar,Type de radar,Date de mise en service,VMA,Latitude,Longitude
0,12001,ETD,31/10/2011 00:00,70.0,45.36100,4.252600
1,12008,ETD,31/10/2011 00:00,80.0,46.41334,4.436502
2,12014,ETD,21/03/2012 00:00,80.0,46.61972,0.345030
3,12015,ETD,28/03/2012 00:00,80.0,46.61800,0.356000
4,12016,ETD,10/02/2012 00:00,80.0,48.05400,6.587000
...,...,...,...,...,...,...
3304,FE391502,ETPN,26/06/2015 00:00,NaN,48.53771,2.374890
3305,FE391503,ETPN,11/03/2016 00:00,NaN,48.56515,2.171450
3306,FE391504,ETPN,16/09/2016 00:00,NaN,48.56460,2.172040
3307,FE395501,ETPN,08/10/2014 00:00,NaN,48.97523,2.336390
3308,FE395502,ETPN,08/10/2014 00:00,NaN,48.97519,2.337510

In [43]:
print(radar_df.columns.tolist())

['Numéro de radar', 'Type de radar', 'Date de mise en service', 'VMA ', 'Latitude', ' Longitude']

In [44]:
radar_df.columns = radar_df.columns.str.lower()

radar_df = radar_df.rename(columns={'numéro de radar': 'numero de radar'})
radar_df.columns = radar_df.columns.str.strip().str.replace(' ', '_')
radar_df['date_de_mise_en_service'] = pd.to_datetime(radar_df['date_de_mise_en_service']).dt.strftime('%Y-%m-%d')
radar_df['vma'] = radar_df['vma'].fillna('inconnu')

radar_df

C:\Users\cuadr\AppData\Local\Temp\ipykernel_21988\2371317831.py:5: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  radar_df['date_de_mise_en_service'] = pd.to_datetime(radar_df['date_de_mise_en_service']).dt.strftime('%Y-%m-%d')

,numero_de_radar,type_de_radar,date_de_mise_en_service,vma,latitude,longitude
0,12001,ETD,2011-10-31,70.0,45.36100,4.252600
1,12008,ETD,2011-10-31,80.0,46.41334,4.436502
2,12014,ETD,2012-03-21,80.0,46.61972,0.345030
3,12015,ETD,2012-03-28,80.0,46.61800,0.356000
4,12016,ETD,2012-02-10,80.0,48.05400,6.587000
...,...,...,...,...,...,...
3304,FE391502,ETPN,2015-06-26,inconnu,48.53771,2.374890
3305,FE391503,ETPN,2016-03-11,inconnu,48.56515,2.171450
3306,FE391504,ETPN,2016-09-16,inconnu,48.56460,2.172040
3307,FE395501,ETPN,2014-10-08,inconnu,48.97523,2.336390
3308,FE395502,ETPN,2014-10-08,inconnu,48.97519,2.337510

In [45]:
radar_df.to_csv('radar_clean', index=False, sep=';', encoding='utf-8-sig')